# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
clone: 
  depth: full
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            # This gets executed when merging a PR to master branch
            - npm install
            - npm test
            - npm run build:production # or your build cmd for prod
            - git add -A
            - git commit -m "production build"
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP_NAME.git master